/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIHelloWorld */

#ifndef _Included_JNIHelloWorld
#define _Included_JNIHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIHelloWorld
 * Method:    printHelloWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIHelloWorld_printHelloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
